name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag minimal_protoc_env:$(date +%s)
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_LOGIN_NAME }}" --password-stdin
    - name: Push the Docker image
      run: |
        IMAGE_ID=minimal_protoc_env
        IMAGE_TAG=$(date +%s)
        DOCKER_USERNAME=${{ secrets.DOCKER_REGISTRY_LOGIN_NAME }}
        docker tag $IMAGE_ID $DOCKER_USERNAME/$IMAGE_ID:$IMAGE_TAG
        docker push $DOCKER_USERNAME/$IMAGE_ID:$IMAGE_TAG
