name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Prepare
      id: prep
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_REGISTRY_LOGIN_NAME }}/minimal_protoc_env
        echo ::set-output name=tagged_image_latest::${IMAGE_NAME}:latest
        echo ::set-output name=tagged_image_timestamp::${TIMESTAMP_TAG}:${{ steps.date.outputs.date }}
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_REGISTRY_LOGIN_NAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.prep.outputs.tagged_image_timestamp }}
          ${{ steps.prep.outputs.tagged_image_latest }}
        